
= Hall of Fame

Best HPO results by model.

All results created with the configurations in `HPO/tests/MODEL` unless otherwise noted.

== Campaigns

These are our standardized HPO sizes.

Population size started at `P` (`POPULATION_SIZE`),
and the HPO was run for `G` iterations (generations) (`NUM_ITERATIONS`).

* *SMALL:*  Lambda:        P=4,  G=3
* *MEDIUM:* Polaris Debug: P=16, G=4
* *LARGE:*  Polaris:       P=80, G=10

== Files

Each model result contains, for `N` as the 2nd largest rank (the rank running the DEAP algorithm):

`metadata.txt`::
Hostname, user, directory names, and other high-level metadata for the run.

`cfg-hpo-settings.sh`::
The input settings used for the test

`cfg-hpo-parameter-space.json`::
The input HPO search space for the test

`best-N.json`::
The JSON fragment with the best hyperparameters

`fitness-N.txt`::
The float value for the best fitness value for the case in `best-N.json`

`out-N.txt`::
The DEAP stdout log

`deap-N.log`::
The DEAP log data structure- basically a table with per-iteration statistics

`population-N.txt`::
The JSON fragments for the population in the final iteration

`fitnesses-N.txt`::
The fitness floats for each member of the final population

`hpo.csv`::
From https://github.com/ECP-CANDLE/Supervisor/tree/develop/scripts#hpo-table

== Plots

We can reuse these tools:

https://github.com/emews/mela/tree/master/deap

== Examples

=== Installation

. Clone Supervisor branch `develop`
. Add `Supervisor/bin` to `PATH`

=== LGBM

==== Preprocess

Set `CANDLE_DATA_DIR` and run:

----
IMAGE=/software/improve/images/lgbm_0.6.0.sif
RAW_DATA_DIR=$CANDLE_DATA_DIR
DATA_SOURCE=gCSI

A=( --bind ${RAW_DATA_DIR}:/candle_data_dir
    ${IMAGE} preprocess.sh /candle_data_dir \
             --train_split_file ${DATA_SOURCE}_split_0_train.txt \
             --val_split_file ${DATA_SOURCE}_split_0_val.txt \
             --test_split_file ${DATA_SOURCE}_split_0_test.txt \
             --ml_data_outdir /candle_data_dir/HPO/LGBM/$DATA_SOURCE
  )

set -x
time singularity exec --nv $A
----

==== Run

----
$ supervisor lambda GA cfg-lgbm-1.sh
----

==== Output

Supervisor creates output directories:

. `D=$CANDLE_DATA_DIR/output/lgbm_0.6.0/EXP...`
. `E=$CANDLE_DATA_DIR/lgbm_0.6.0/Output/EXP...`

* Per-rank logs are in `$D/out/out-*.txt`
* Model logs are in `$E/run_*/model.log`
* DEAP output is in the 2nd-highest-rank `out-*.txt`

==== Modifying

* Edit settings in `test/cfg-lgbm-1.sh`
* Edit hyperparameters in `data/lgbm_param_space-1.json`
